/*
 * DevNest Portal API (OpenAPI 3.0)
 *
 * The DevNest Portal API endpoints definitions based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.0
 * Contact: contact@devnest.ro
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SettingsNotifications struct {

	EmployeeSheetReminder bool `json:"employeeSheetReminder,omitempty"`

	CompleteProjectSheets bool `json:"completeProjectSheets,omitempty"`

	IndividualSheets bool `json:"individualSheets,omitempty"`

	UpcomingEndingDates *SettingsNotificationsUpcomingEndingDates `json:"upcomingEndingDates,omitempty"`
}
